version: '3'
services:
  immo:
    build:
      context: .
      args:
        IMAGE_NAME: ${IMAGE_NAME}
        TAG: ${TAG}

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
    ports:
      - "8000:8000"
