version: '3'
services:
  immo:
    build:
      context: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
    ports:
      - "8000:8000"
