name: Deploy

on:
  workflow_run:
    workflows: ["CI build"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo hi
